# Simple workflow for deploying static content to GitHub Pages
name: Publish GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [$default-branch]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: Install Node Packages
        run: npm ci

      - name: Build the Page
        run: npm run build

      - name: Build ZIP archive
        run: mv dist agama-validator && zip -r agama-validator.zip agama-validator -x "*.map" &&
             mv agama-validator.zip agama-validator/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # the "path" parameter needs a directory
          path: agama-validator

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
